### ISSUE TITLE
Issue with running rollmatch command using a renamed "treat" variable

### ISSUE THREAD

**Issue by scotopotomas** [RTIInternational/rollmatch#5]
Hi, 
I was using rollmatch and ran into an error where the actual rollmatch function was not working if I renamed my treatment variable anything other than "treat".  This happened twice, when I used a treatment variable named, "Treat" and again when I used one called, "test", the issue appeared to be resolved when I renamed the treatment variable to "treat".

I've attached the traceback and the code that originally caused the error, please let me know if you need any additional detail.

Thank you,
Scott Fry

**Traceback:**
> traceback()
15: stop(list(message = "Column `treat` is unknown", call = NULL, 
        cppstack = NULL))
14: grouped_df_impl(data, unname(vars), drop)
13: grouped_df(groups$data, groups$group_names, .drop)
12: group_by.data.frame(., treat)
11: dplyr::group_by(., treat)
10: function_list[[k]](value)
9: withVisible(function_list[[k]](value))
8: freduce(value, `_function_list`)
7: `_fseq`(`_lhs`)
6: eval(quote(`_fseq`(`_lhs`)), env, env)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
4: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3: scored_data[, vars] %>% dplyr::group_by(treat)
2: add_balance_table(scored_data = scored_data, vars = vars, tm = tm, 
       id = id, combined_output = combined_output, treat = treat, 
       matches = matches)
1: rollmatch(HCP_Medicare_Scored, data = HCP_Medicare_For_Model, 
       treat = "test", tm = "quarter", entry = "entry_q", id = "MemberID", 
       vars = Medicare_Variables, lookback = 1, alpha = 0.2, standard_deviation = "average", 
       num_matches = 5, replacement = FALSE)

**R Code:**
HCP_Medicare_For_Model_Reduced <- reduce_data(data = HCP_Medicare_For_Model,
                                              treat = "test",
                                              tm = "quarter",
                                              entry = "entry_q",
                                              id = "MemberID",
                                              lookback = 1)

Medicare_Formula <- as.formula(test ~ heartFailFlg + renalFailureFlg + COPDFlg + inPatientHospitalCnt + emergencyVisitCnt +
                                 nursingServiceFlg + chronicConditionCnt + majorADGCnt + acgResourceUtilizationDimId +
                                 isMale + isFrail + age)

Medicare_Variables <- all.vars(Medicare_Formula)

HCP_Medicare_Scored <- score_data(reduced_data = HCP_Medicare_For_Model_Reduced,
                                  model_type = "logistic",
                                  match_on = "logit",
                                  fm = Medicare_Formula,
                                  treat = "test",
                                  tm = "quarter",
                                  entry = "entry_q",
                                  id = "MemberID")

HCP_Medicare_Output <- rollmatch(HCP_Medicare_Scored, 
                                 data = HCP_Medicare_For_Model,
                                 treat = "test",
                                 tm = "quarter",
                                 entry = "entry_q",
                                 id = "MemberID",
                                 vars = Medicare_Variables,
                                 lookback = 1,
                                 alpha = .2,
                                 standard_deviation = "average",
                                 num_matches = 5,
                                 replacement = FALSE)

**Comment by rchew** [comment]
Hi Scott,

Thanks for catching this!  It looks like we were using the default version of the `dplyr` functions that do not support Standard Evaluation and so the variable names were not being evaluated dynamically (see [this blog post](https://datascience.blog.wzb.eu/2016/09/27/dynamic-columnvariable-names-with-dplyr-using-standard-evaluation-functions/) for some additional context).  We've fixed in e0e7738 -- let us know if this is still an issue for you and we can re-open the thread.
