### ISSUE TITLE
Issue with running rollmatch function and id variable 

### ISSUE THREAD

**Issue by tanjaclark** [RTIInternational/rollmatch#6]
Was using rollmatch function:

```
output <- rollmatch(scored_data, data = enrollment, treat = "intervention",
                    tm = "time", entry = "entry", id = "hsh_id",
                    vars = vars, lookback = 1, alpha = .2,
                    standard_deviation = "average", num_matches = 3,
                    replacement = TRUE)
```

And ran into the following error:
`Unknown or uninitialised column: 'indiv_id'.`

It looks like the error is coming from the make_output function here: 
`all_ids <- unique(scored_data$indiv_id[scored_data[[treat]] == 1])`

Was able to workaround by renaming my id field to indiv_id.

**Comment by rchew** [comment]
That's a good catch -- my initial guess is that the underlying issue is similar to #5.  Will try to diagnose and fix this week.  If you find other instances, please let us know!

**Comment by rchew** [comment]
Hey @tanjaclark,

I'm having trouble re-creating the issue -- do you have a sense what's different in your workflow than what is presented below?

```
# Installing Github version of rollmatch
library(devtools)
devtools::install_github("RTIInternational/rollmatch")

# Load rollmatch
library(rollmatch)

# Load sample dataset
data(package="rollmatch", "rem_synthdata_small")

# Rename ID var to "hsh_id"
names(rem_synthdata_small)[names(rem_synthdata_small) == "indiv_id"] <- "hsh_id"

# Reduce the input dataset size, for matching 
reduced_data <- reduce_data(data = rem_synthdata_small, treat = "treat",
                            tm = "quarter", entry = "entry_q",
                            id = "hsh_id", lookback = 1)

# Choose confounding variables hypothesized to be associated with both treatment and outcome
fm <- as.formula(treat ~ qtr_pmt + yr_pmt + age)
vars <- all.vars(fm)

# Calculate propensity scores for the reduced data
scored_data <- score_data(reduced_data = reduced_data,
                          model_type = "logistic", match_on = "logit",
                          fm = fm, treat = "treat",
                          tm = "quarter", entry = "entry_q", id = "hsh_id")

# Run the rolling entry matching algorithm
output <- rollmatch(scored_data, data=rem_synthdata_small, treat = "treat",
                    tm = "quarter", entry = "entry_q", id = "hsh_id",
                    vars = vars, lookback = 1, alpha = .2,
                    standard_deviation = "average", num_matches = 3,
                    replacement = TRUE)

# View output matches and diagnostics
output
```

**Comment by rchew** [comment]
Going to close this for now -- @tanjaclark feel free to reopen if you're still having issues

**Comment by tanjaclark** [comment]
Hi again, 

I was able to run the code above - not sure why it wasn't running and was throwing up an error when I was using this a few months ago. However, the bug is still clear in the output from the code you commented above: 
`output$total_not_matched ` is NULL when it should be 78569 78696 79225
`output$ids_not_matched` is 0 when it should be 3

Would suggest changing the following line in the make_output function:
` all_ids <- unique(scored_data$id[scored_data[[treat]] == 1])`
To:
 `all_ids <- unique(scored_data[[id]][scored_data[[treat]] == 1])`
Which fixed the bug for me.
